# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pocBeagle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pocBeagle

  pod 'Beagle'
  pod 'YogaKit', :git => 'https://github.com/lucasaraujo/yoga.git'

end
